baseURL: http://szare.ir/
languageCode: en-us
paginate: 6
theme: portio
title: Portio
menu:
  main:
    - name: Home
      url: "#home"
      weight: 1
    - name: About
      url: "#about"
      weight: 2
    - name: Service
      url: "#service"
      weight: 3
    - name: Work
      url: "#portfolio"
      weight: 4
    - name: Resume
      url: "#resume"
      weight: 5
    - name: Skills
      url: "#skills"
      weight: 6
    # - name: Blog
    #   url: "#blog"
    #   weight: 7
    - name: Contact
      url: "#contact"
      weight: 8
  sitemap:
    - name: About me
      url: "#about"
      weight: 1
    # - name: Frequently Ask Question
    - name: service
      url: "#service"
      weight: 2
    # - name: Privacy & Policy
    - name: Work
      url: "#portfolio"
      weight: 3
    # - name: Latest Article
    - name: Resume
      url: "#resume"
      weight: 4
params:
  blogPageURL: blog
  contactLink: contact
  copyright: All right reserved copyright © Portio 2020
  footerLogo: images/contact/widget-logo.png
  fabformURL: https://fabform.io/f/JpTXRUa
  googleAnalytics: G-5SYG768XPS
  logo: images/site-navigation/logo.png
  address:
    address: Iran, Tehran
    email: zaresedighe77@gmail.com
    openingHours: Available from 9am to 3pm 
    #phone: +(448) 833 5272 332
  map:
    APIkey: YOUR GOOGLE MAP API
    latitude: "23.7783741"
    longitude: "90.3746808"
    pinImage: images/pin.png
  social:
    - icon: fa-dribbble
      url: https://dribbble.com/S_Zare/
      weight: 1
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/sedighezare/
      weight: 2
    - icon: fa-instagram
      url: https://www.instagram.com/s.zare.ui/
      weight: 3
    # - icon: fa-twitter-square
    #   url: https://twitter.com/
    #   weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true